name: UpdateReadMeWithPython

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run Fetcher.
      run: |
        python3 /home/hvdm/RabbitService/READMEWorker.py
    - name: Commit Files
      run: |
        git add -A
        git commit -m "😎 Data updated via Action" -a --force
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main  
